version: "3"
services:
  postgresql:
    image: postgresql
    build: postgresql/
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=keycloak
    networks:
      - services-network
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - services-network
  rabbitmq:
    image: rabbitmq
    build: rabbitmq/
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - services-network
  keycloak:
    image: keycloak
    build: keycloak/
    container_name: keycloak
    depends_on:
      - "postgresql"
      - "rabbitmq"
    ports:
      - "8081:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgresql
      - DB_DATABASE=keycloak
      - DB_USER=postgres
      - DB_SCHEMA=public
      - DB_PASSWORD=postgres123
      - RABBITMQ_EVENT_LISTENER_HOST=rabbitmq
    networks:
      - services-network  
networks:
  services-network:
    driver: "bridge"