server:
  port: ${SERVER_PORT:8082}
spring:
  data:
    mongodb:
      host: ${DATABASE_HOST:localhost}
      port: ${DATABASE_PORT:27017}
      database: ${DATABASE_NAME:usersdb}
keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8081/auth}
  realm: ${KEYCLOAK_REALM:application}
  client-id: ${KEYCLOAK_CLIENT_ID:users-service}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:91c3b95d-b969-4ebf-b15b-36aa694de895}
collections:
  users: ${USERS_COLLECTION_NAME:users}

